### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by bduggan** [Raku/rakubrew.org#12]
Hi Folks,

Looks like rakubrew.org is down

thanks

**Comment by patrickbkr** [comment]
@ping rba

**Comment by rba** [comment]
@patrickbkr 
whois says: 
...
Name Server: EXPIRED-DOMAIN.DOMROBOT.COM
Name Server: PLEASE-RENEW-DOMAIN.DOMROBOT.COM
...

Afaik you have registered the domain?

May I take it over?

**Comment by patrickbkr** [comment]
@rba Yes!

**Comment by patrickbkr** [comment]
@rba I sent you the Auth-Code via IRC.

**Comment by rba** [comment]
@patrickbkr Domain name transfer initiated. Please check if you need to confirm by email.

**Comment by bduggan** [comment]
it's back in action.  well done!

**Comment by patrickbkr** [comment]
@rba I have granted the transfer request.
