### ISSUE TITLE
Installation instructions for Linux

### ISSUE THREAD

**Issue by pmqs** [Raku/rakubrew.org#13]
I'm attempting to install on Linux, but there are missing instructions on  https://rakubrew.org/
 
First the `Installation` section. This only has instructions for a windows install.

```
Installation
============

On `CMD` you need to download https://rakubrew.org/install-on-cmd.bat and then
execute that script in a CMD terminal.

On `PowerShell` just copy and paste the following piece of code into a
Powershell window (Don't forget the "." at the start of the command!):

    . {iwr -useb https://rakubrew.org/install-on-powershell.ps1 } | iex
```

So, onto  the next section

```
Bare bones installation
=======================

If the above installation script somehow doesn't work for you, you can install
rakubrew manually.

First download the right rakubrew executable for your platform:

    Unix-ish: https://rakubrew.org/perl/rakubrew
    Mac OS:   https://rakubrew.org/macos/rakubrew
    Windows:  https://rakubrew.org/win/rakubrew.exe

Put that file into a folder that's in your `PATH` and run

    rakubrew mode shim

That's all!
```

I downloaded https://rakubrew.org/perl/rakubrew, but when I run `rakubrew`  I get

```
$ rakudobrew 
bash: /home/paul/.rakudobrew/bin/rakudobrew: No such file or directory
```

What am I missing?

**Comment by JJ** [comment]
El mar, 22 dic 2020 a las 10:56, Paul Marquess (<notifications@github.com>)
escribió:

> I'm attempting to install on Linux, but there are missing instructions on
> https://rakubrew.org/
>
> First the Installation section. This only has instructions for a windows
> install.
>
> Installation
> ============
>
> On `CMD` you need to download https://rakubrew.org/install-on-cmd.bat and then
> execute that script in a CMD terminal.
>
> On `PowerShell` just copy and paste the following piece of code into a
> Powershell window (Don't forget the "." at the start of the command!):
>
>     . {iwr -useb https://rakubrew.org/install-on-powershell.ps1 } | iex
>
> So, onto the next section
>
> Bare bones installation
> =======================
>
> If the above installation script somehow doesn't work for you, you can install
> rakubrew manually.
>
> First download the right rakubrew executable for your platform:
>
>     Unix-ish: https://rakubrew.org/perl/rakubrew
>     Mac OS:   https://rakubrew.org/macos/rakubrew
>     Windows:  https://rakubrew.org/win/rakubrew.exe
>
> Put that file into a folder that's in your `PATH` and run
>
>     rakubrew mode shim
>
> That's all!
>
> I downloaded https://rakubrew.org/perl/rakubrew, but when I run rakubrew
> I get
>
> $ rakudobrew
> bash: /home/paul/.rakudobrew/bin/rakudobrew: No such file or directory
>
>
Did you realize you've downloaded rakubrew but are running rakudobrew?

**Comment by patrickbkr** [comment]
@pmqs rakubrew.org does OS detection and displays instructions for the respective OS. Did you access the page from a Windows computer or have a UserAgent switcher active in your browser? If accessed from a Linux computer proper Linux install instructions should be displayed.

I probably should put some links on the page to be able to manually set the version to be displayed...

**Comment by pmqs** [comment]
> Did you realize you've downloaded rakubrew but are running rakudobrew?

Duh!  Bad case of pilot error.

**Comment by pmqs** [comment]
> @pmqs rakubrew.org does OS detection and displays instructions for the respective OS. Did you access the page from a Windows computer or have a UserAgent switcher active in your browser? If accessed from a Linux computer proper Linux install instructions should be displayed.

@patrickbkr Yes, that's exactly what I did. Loaded the page under Linux & it looks fine.

One comment about the colour scheme for the web page. On Linux the background is black and the text is easily readable. On Windows the background is a bluish purple mix. Makes it very difficult to read the text (particularly the hyperlinks).

> I probably should put some links on the page to be able to manually set the version to be displayed...

Yeah, I think that would help.

**Comment by patrickbkr** [comment]
@pmqs WRT to the color scheme. The Windows colors mimic those of the default Powershell console. So the webpage looks as good or bad as the console does. :-P IIRC the new PS7 console has an a bit updated color scheme, if that's true we could update to that...
