### ISSUE TITLE
It is possible to install, custom raku compiled

### ISSUE THREAD

**Issue by anquegi** [Raku/rakubrew.org#17]
You can install raku 

rakubrew build[-rakudo] [<backend>] [<tag>|<branch>|<sha-1>]

from branch or sha directly, but it should be possible to install from your custom fork, or custom directory.

how can this be achieved?

**Comment by patrickbkr** [comment]
Rakubrew currently doesn't have the ability to build from custom forks/directories. Rakubrew has a functionality to register a custom installation and then manage it though.
To do so you need to build and install your fork manually (basically `./Configure.pl && make install`) and then `rakubrew register my-fork /path/to/the/custom/forks/install/dir`.
Does that help?

**Comment by anquegi** [comment]
thanks @patrickbkr , for the detailed instructions I will give it a try, I didn't get the register functionality
