### ISSUE TITLE
Fix for dash shell

### ISSUE THREAD

**Issue by rbt** [Raku/rakubrew.org#7]
As mentioned in #6 the Debian shell fails to execute install-on-perl.sh because it doesn't have the set -o pipefail option.

`set -o` outputs a list of options available, so simply look to see if that option is supported before trying to set it.

```
*** /tmp/orig	2020-07-08 20:30:08.494403369 -0400
--- /tmp/install-on-perl.sh	2020-07-08 20:30:21.810601543 -0400
***************
*** 1,7 ****
  #!/usr/bin/env sh
  
  set -o errexit
! set -o pipefail
  
  for cmd in "rakudobrew", "p6env"; do
      if command -v $cmd >/dev/null 2>&1 ; then
--- 1,9 ----
  #!/usr/bin/env sh
  
  set -o errexit
! if [ "`set -o | grep 'pipefail'`" != "" ]; then
! 	set -o pipefail
! fi
  
  for cmd in "rakudobrew", "p6env"; do
      if command -v $cmd >/dev/null 2>&1 ; then
```

**Comment by patrickbkr** [comment]
This is actually fixed in [899c8c8e41](https://github.com/Raku/rakubrew.org/commit/899c8c8e416962b239a8aec5266f9f6b9b18122a), but isn't yet deployed to the website. I'm looking into speeding up the deployment process. Sorry for the inconvenience!
Closing as this actually is already fixed.
